# Generated by Django 4.1.5 on 2023-01-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
