# Generated by Django 4.1.5 on 2023-01-16 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0002_alter_appuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{3}-\\d{3}-\\d{4}$', message='Invalid phone')]),
        ),
    ]
